project 'JetBeepExample.xcodeproj'
platform :ios, '13.0'
inhibit_all_warnings!

target 'JetBeepExample' do
    use_frameworks!
    # pod 'JetBeepFramework'
   pod 'JetBeepFramework', path: '../../iOS'
    pod 'Alamofire'
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end

